In [7]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\salir\desktop\dano_final\venv\lib\site-packages (3.1.2)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: et-xmlfile in c:\users\salir\desktop\dano_final\venv\lib\site-packages (from openpyxl) (1.1.0)

In [47]:
import pandas as pd

In [48]:
df = pd.read_excel("cashback.xlsx")
df_moscow = df[df["город_проживания"] == "Москва"]
df_saint = df[df["город_проживания"] == "Санкт-Петербург"]
df_regions = df.loc[((df["город_проживания"] != "Москва") & (df["город_проживания"] != "Санкт-Петербург"))]
print(df_moscow,df_saint, df_regions)

       ключ_клиента регион_проживания город_проживания  возраст  пол  \
0              1889            Москва           Москва       50    M
1              1889            Москва           Москва       50    M
2              1889            Москва           Москва       50    M
3              1889            Москва           Москва       50    M
4              1889            Москва           Москва       50    M
...             ...               ...              ...      ...  ...
59821    1005319581            Москва           Москва       37  NaN
59822    1005319581            Москва           Москва       37  NaN
59823    1005319581            Москва           Москва       37  NaN
59824    1005319581            Москва           Москва       37  NaN
59825    1005319581            Москва           Москва       37  NaN

      месяц_покупок  оборот_аптеки  оборот_рестораны  оборот_одежда_и_обувь  \
0        2023-04-01        18993.0           99900.0                 3294.0
1        2023-05-01        37807.0           92424.0                    NaN
2        2023-06-01        20791.0          124800.0                51246.0
3        2023-07-01       131129.0           18060.0                78120.0
4        2023-08-01        44096.0          198480.0                19080.0
...             ...            ...               ...                    ...
59821    2023-05-01          657.0           54375.0                    NaN
59822    2023-06-01            NaN          128070.0                    NaN
59823    2023-07-01         5919.0           26085.0                    NaN
59824    2023-08-01         1705.0          111690.0                    NaN
59825    2023-09-01         2832.0           89370.0                    NaN

       оборот_автоуслуги  ...  кэшбэк_развлечения  кэшбэк_жд_билеты  \
0                    NaN  ...                 NaN               NaN
1                 6750.0  ...                 NaN               NaN
2                67490.0  ...                 NaN               NaN
3                 2400.0  ...                 NaN               NaN
4               147705.0  ...                 NaN               NaN
...                  ...  ...                 ...               ...
59821                NaN  ...                 NaN               NaN
59822                NaN  ...               270.0               NaN
59823                NaN  ...              1365.0               NaN
59824                NaN  ...                 NaN               NaN
59825                NaN  ...                 NaN               NaN

       кэшбэк_образование  кэшбэк_дом_и_ремонт  кэшбэк_спорттовары  \
0                     NaN                  NaN                 NaN
1                     NaN                  NaN                 NaN
2                     NaN                  NaN                 NaN
3                     NaN                  NaN                 NaN
4                     NaN                  NaN                 NaN
...                   ...                  ...                 ...
59821                 NaN                  NaN                 NaN
59822                 NaN                  NaN                 NaN
59823                 NaN                  NaN                 NaN
59824                 NaN                  NaN                 NaN
59825                 NaN                  NaN                 NaN

       кэшбэк_животные  кэшбэк_цветы  кэшбэк_фастфуд  кэшбэк_каршеринг  \
0                  NaN           NaN             NaN               NaN
1                  NaN           NaN             NaN               NaN
2                  NaN           NaN             NaN               NaN
3                  NaN           NaN             NaN               NaN
4                  NaN           NaN             NaN               NaN
...                ...           ...             ...               ...
59821              NaN           NaN             NaN               NaN
59822              NaN           NaN             NaN               NaN
59823              NaN           NaN             NaN               NaN
59824              NaN           NaN             NaN               NaN
59825              NaN           NaN             NaN               NaN

       кэшбэк_аренда_авто
0                     NaN
1                     NaN
2                     NaN
3                     NaN
4                     NaN
...                   ...
59821                 NaN
59822                 NaN
59823                 NaN
59824                 NaN
59825                 NaN

[29088 rows x 57 columns]        ключ_клиента регион_проживания город_проживания  возраст пол  \
30           283148   Санкт-Петербург  Санкт-Петербург       43   F
31           283148   Санкт-Петербург  Санкт-Петербург       43   F
32           283148   Санкт-Петербург  Санкт-Петербург       43   F
33           283148   Санкт-Петербург  Санкт-Петербург       43   F
34           283148   Санкт-Петербург  Санкт-Петербург       43   F
...             ...               ...              ...      ...  ..
59797    1002982745   Санкт-Петербург  Санкт-Петербург       51   F
59798    1002982745   Санкт-Петербург  Санкт-Петербург       51   F
59799    1002982745   Санкт-Петербург  Санкт-Петербург       51   F
59800    1002982745   Санкт-Петербург  Санкт-Петербург       51   F
59801    1002982745   Санкт-Петербург  Санкт-Петербург       51   F

      месяц_покупок  оборот_аптеки  оборот_рестораны  оборот_одежда_и_обувь  \
30       2023-04-01         1282.0               NaN                92517.0
31       2023-05-01         8853.0             147.0                38472.0
32       2023-06-01         9510.0               NaN               104711.0
33       2023-07-01        11290.0               NaN                74140.0
34       2023-08-01        12558.0            1410.0               149589.0
...             ...            ...               ...                    ...
59797    2023-05-01            NaN           28788.0                 5130.0
59798    2023-06-01         6354.0           15894.0                11832.0
59799    2023-07-01            NaN           31500.0                15492.0
59800    2023-08-01         8436.0           15240.0                 9291.0
59801    2023-09-01        12948.0            8622.0               167259.0

       оборот_автоуслуги  ...  кэшбэк_развлечения  кэшбэк_жд_билеты  \
30                   NaN  ...                 NaN               NaN
31                   NaN  ...                 NaN               NaN
32                   NaN  ...                 NaN               NaN
33                   NaN  ...               351.0               NaN
34                   NaN  ...               447.0               NaN
...                  ...  ...                 ...               ...
59797              486.0  ...                 NaN               NaN
59798                NaN  ...                 NaN               NaN
59799                NaN  ...                 NaN               NaN
59800             4200.0  ...                 NaN               NaN
59801                NaN  ...                 NaN               NaN

       кэшбэк_образование  кэшбэк_дом_и_ремонт  кэшбэк_спорттовары  \
30                    NaN                  NaN                 NaN
31                    NaN                  NaN                 NaN
32                    NaN              14733.0                 NaN
33                    NaN                  NaN                 NaN
34                    NaN                  NaN                 NaN
...                   ...                  ...                 ...
59797                 NaN                  NaN                 NaN
59798                 NaN                  NaN                 NaN
59799                 NaN                  NaN                 NaN
59800                 NaN                  NaN                 NaN
59801                 NaN                  NaN                 NaN

       кэшбэк_животные  кэшбэк_цветы  кэшбэк_фастфуд  кэшбэк_каршеринг  \
30                 NaN           NaN             NaN               NaN
31                 NaN         243.0             NaN               NaN
32                 NaN           NaN             NaN               NaN
33                 NaN           NaN             NaN               NaN
34                 NaN           NaN             NaN               NaN
...                ...           ...             ...               ...
59797              NaN           NaN             NaN               NaN
59798              NaN           NaN             NaN               NaN
59799              NaN         246.0             NaN               NaN
59800              NaN           NaN             NaN               NaN
59801              NaN           NaN             NaN               NaN

       кэшбэк_аренда_авто
30                    NaN
31                    NaN
32                    NaN
33                    NaN
34                    NaN
...                   ...
59797                 NaN
59798                 NaN
59799                 NaN
59800                 NaN
59801                 NaN

[6342 rows x 57 columns]        ключ_клиента     регион_проживания город_проживания  возраст пол  \
12           191765  Белгородская область         Белгород       47   F
13           191765  Белгородская область         Белгород       47   F
14           191765  Белгородская область         Белгород       47   F
15           191765  Белгородская область         Белгород       47   F
16           191765  Белгородская область         Белгород       47   F
...             ...                   ...              ...      ...  ..
59815    1003493065    Республика Карелия     Петрозаводск       42   M
59816    1003493065    Республика Карелия     Петрозаводск       42   M
59817    1003493065    Республика Карелия     Петрозаводск       42   M
59818    1003493065    Республика Карелия     Петрозаводск       42   M
59819    1003493065    Республика Карелия     Петрозаводск       42   M

      месяц_покупок  оборот_аптеки  оборот_рестораны  оборот_одежда_и_обувь  \
12       2023-04-01         2073.0            2403.0                    NaN
13       2023-05-01        10586.0            6468.0                97923.0
14       2023-06-01        10611.0               NaN                 1080.0
15       2023-07-01        30672.0            3642.0                53415.0
16       2023-08-01        22316.0               NaN                 2610.0
...             ...            ...               ...                    ...
59815    2023-05-01        18228.0          153096.0                14409.0
59816    2023-06-01        24807.0          163884.0                38337.0
59817    2023-07-01        16195.0          143451.0                25680.0
59818    2023-08-01        23215.0           88242.0                39810.0
59819    2023-09-01        23563.0           24678.0                35783.0

       оборот_автоуслуги  ...  кэшбэк_развлечения  кэшбэк_жд_билеты  \
12                1350.0  ...                 NaN               NaN
13                   NaN  ...                 NaN               NaN
14                   NaN  ...                 NaN               NaN
15                5187.0  ...                 NaN               NaN
16                   NaN  ...                 NaN               NaN
...                  ...  ...                 ...               ...
59815                NaN  ...                 NaN               NaN
59816           135000.0  ...                96.0               NaN
59817            17970.0  ...               225.0               NaN
59818             2145.0  ...               150.0               NaN
59819                NaN  ...                 NaN               NaN

       кэшбэк_образование  кэшбэк_дом_и_ремонт  кэшбэк_спорттовары  \
12                    NaN                  NaN                 NaN
13                    NaN                  NaN                 NaN
14                    NaN                  NaN                 NaN
15                    NaN                  NaN                 NaN
16                    NaN                  NaN                 NaN
...                   ...                  ...                 ...
59815                 NaN                  NaN                 NaN
59816                 NaN                  NaN                 NaN
59817                 NaN                  NaN                 NaN
59818                 NaN                  NaN                 NaN
59819                 NaN                465.0                 NaN

       кэшбэк_животные  кэшбэк_цветы  кэшбэк_фастфуд  кэшбэк_каршеринг  \
12                 NaN           NaN             NaN               NaN
13                39.0           NaN             NaN               NaN
14               405.0           NaN             NaN               NaN
15                 NaN           NaN             NaN               NaN
16                27.0           NaN             NaN               NaN
...                ...           ...             ...               ...
59815              NaN           NaN             NaN               NaN
59816              NaN           NaN             NaN               NaN
59817              NaN           NaN             NaN               NaN
59818              NaN           NaN             NaN               NaN
59819              NaN           NaN             NaN               NaN

       кэшбэк_аренда_авто
12                    NaN
13                    NaN
14                    NaN
15                    NaN
16                    NaN
...                   ...
59815                 NaN
59816                 NaN
59817                 NaN
59818                 NaN
59819                 NaN

[24396 rows x 57 columns]

In [69]:
df_moscow_gd = df_moscow[["ключ_клиента", "месяц_покупок", "оборот_жд_билеты", "активация_кэшбэка_жд_билеты"]].fillna(0)
df_moscow_edc = df_moscow[["ключ_клиента", "месяц_покупок", "оборот_образование", "активация_кэшбэка_образование"]].fillna(0)
df_moscow_house = df_moscow[["ключ_клиента", "месяц_покупок", "оборот_дом_и_ремонт", "активация_кэшбэка_дом_и_ремонт"]].fillna(0) 
df_moscow_sport =  df_moscow[["ключ_клиента", "месяц_покупок", "оборот_спорттовары", "активация_кэшбэка_спорттовары"]].fillna(0) 
df_moscow_animals = df_moscow[["ключ_клиента", "месяц_покупок", "оборот_животные", "активация_кэшбэка_животные"]].fillna(0)
df_moscow_flowers = df_moscow[["ключ_клиента", "месяц_покупок", "оборот_цветы", "активация_кэшбэка_цветы"]].fillna(0) 
df_moscow_fastfood = df_moscow[["ключ_клиента", "месяц_покупок", "оборот_фастфуд", "активация_кэшбэка_фастфуд"]].fillna(0) 
df_moscow_carsharing = df_moscow[["ключ_клиента", "месяц_покупок", "оборот_каршеринг", "активация_кэшбэка_каршеринг"]].fillna(0) 
df_moscow_auto = df_moscow[["ключ_клиента", "месяц_покупок", "оборот_аренда_авто", "активация_кэшбэка_аренда_авто"]].fillna(0) 
print(len(df_moscow_gd.groupby("ключ_клиента")))

4848

In [50]:
df_saint_gd = df_saint[["ключ_клиента", "месяц_покупок", "оборот_жд_билеты", "активация_кэшбэка_жд_билеты"]].fillna(0) 
df_saint_edc = df_saint[["ключ_клиента", "месяц_покупок", "оборот_образование", "активация_кэшбэка_образование"]].fillna(0)
df_saint_house = df_saint[["ключ_клиента", "месяц_покупок", "оборот_дом_и_ремонт", "активация_кэшбэка_дом_и_ремонт"]].fillna(0) 
df_saint_sport =  df_saint[["ключ_клиента", "месяц_покупок", "оборот_спорттовары", "активация_кэшбэка_спорттовары"]].fillna(0) 
df_saint_animals = df_saint[["ключ_клиента", "месяц_покупок", "оборот_животные", "активация_кэшбэка_животные"]].fillna(0)
df_saint_flowers = df_saint[["ключ_клиента", "месяц_покупок", "оборот_цветы", "активация_кэшбэка_цветы"]].fillna(0) 
df_saint_fastfood = df_saint[["ключ_клиента", "месяц_покупок", "оборот_фастфуд", "активация_кэшбэка_фастфуд"]].fillna(0) 
df_saint_carsharing = df_saint[["ключ_клиента", "месяц_покупок", "оборот_каршеринг", "активация_кэшбэка_каршеринг"]].fillna(0) 
df_saint_auto = df_saint[["ключ_клиента", "месяц_покупок", "оборот_аренда_авто", "активация_кэшбэка_аренда_авто"]].fillna(0)

In [51]:
df_regions_gd = df_regions[["ключ_клиента", "месяц_покупок", "оборот_жд_билеты", "активация_кэшбэка_жд_билеты"]].fillna(0) 
df_regions_edc = df_regions[["ключ_клиента", "месяц_покупок", "оборот_образование", "активация_кэшбэка_образование"]].fillna(0)
df_regions_house = df_regions[["ключ_клиента", "месяц_покупок", "оборот_дом_и_ремонт", "активация_кэшбэка_дом_и_ремонт"]].fillna(0) 
df_regions_sport =  df_regions[["ключ_клиента", "месяц_покупок", "оборот_спорттовары", "активация_кэшбэка_спорттовары"]].fillna(0) 
df_regions_animals = df_regions[["ключ_клиента", "месяц_покупок", "оборот_животные", "активация_кэшбэка_животные"]].fillna(0)
df_regions_flowers = df_regions[["ключ_клиента", "месяц_покупок", "оборот_цветы", "активация_кэшбэка_цветы"]].fillna(0) 
df_regions_fastfood = df_regions[["ключ_клиента", "месяц_покупок", "оборот_фастфуд", "активация_кэшбэка_фастфуд"]].fillna(0) 
df_regions_carsharing = df_regions[["ключ_клиента", "месяц_покупок", "оборот_каршеринг", "активация_кэшбэка_каршеринг"]].fillna(0) 
df_regions_auto = df_regions[["ключ_клиента", "месяц_покупок", "оборот_аренда_авто", "активация_кэшбэка_аренда_авто"]].fillna(0)

In [52]:
df_moscow_gd = df_moscow_gd[df_moscow_gd.duplicated(subset=["ключ_клиента"], keep=False)]
df_moscow_edc = df_moscow_edc[df_moscow_edc.duplicated(subset=["ключ_клиента"], keep=False)]
df_moscow_house = df_moscow_house[df_moscow_house.duplicated(subset=["ключ_клиента"], keep=False)]
df_moscow_sport = df_moscow_sport[df_moscow_sport.duplicated(subset=["ключ_клиента"], keep=False)]
df_moscow_animals = df_moscow_animals[df_moscow_animals.duplicated(subset=["ключ_клиента"], keep=False)]
df_moscow_flowers = df_moscow_flowers[df_moscow_flowers.duplicated(subset=["ключ_клиента"], keep=False)]
df_moscow_fastfood = df_moscow_fastfood[df_moscow_fastfood.duplicated(subset=["ключ_клиента"], keep=False)]
df_moscow_carsharing = df_moscow_carsharing[df_moscow_carsharing.duplicated(subset=["ключ_клиента"], keep=False)]
df_moscow_auto= df_moscow_auto[df_moscow_auto.duplicated(subset=["ключ_клиента"], keep=False)]
df_saint_gd = df_saint_gd[df_saint_gd.duplicated(subset=["ключ_клиента"], keep=False)]
df_saint_edc = df_saint_edc[df_saint_edc.duplicated(subset=["ключ_клиента"], keep=False)]
df_saint_house = df_saint_house[df_saint_house.duplicated(subset=["ключ_клиента"], keep=False)]
df_saint_sport = df_saint_sport[df_saint_sport.duplicated(subset=["ключ_клиента"], keep=False)]
df_saint_animals = df_saint_animals[df_saint_animals.duplicated(subset=["ключ_клиента"], keep=False)]
df_saint_flowers = df_saint_flowers[df_saint_flowers.duplicated(subset=["ключ_клиента"], keep=False)]
df_saint_fastfood = df_saint_fastfood[df_saint_fastfood.duplicated(subset=["ключ_клиента"], keep=False)]
df_saint_carsharing = df_saint_carsharing[df_saint_carsharing.duplicated(subset=["ключ_клиента"], keep=False)]
df_saint_auto= df_saint_auto[df_saint_auto.duplicated(subset=["ключ_клиента"], keep=False)]
df_regions_gd = df_regions_gd[df_regions_gd.duplicated(subset=["ключ_клиента"], keep=False)]
df_regions_edc = df_regions_edc[df_regions_edc.duplicated(subset=["ключ_клиента"], keep=False)]
df_regions_house = df_regions_house[df_regions_house.duplicated(subset=["ключ_клиента"], keep=False)]
df_regions_sport = df_regions_sport[df_regions_sport.duplicated(subset=["ключ_клиента"], keep=False)]
df_regions_animals = df_regions_animals[df_regions_animals.duplicated(subset=["ключ_клиента"], keep=False)]
df_regions_flowers = df_regions_flowers[df_regions_flowers.duplicated(subset=["ключ_клиента"], keep=False)]
df_regions_fastfood = df_regions_fastfood[df_regions_fastfood.duplicated(subset=["ключ_клиента"], keep=False)]
df_regions_carsharing = df_regions_carsharing[df_regions_carsharing.duplicated(subset=["ключ_клиента"], keep=False)]
df_regions_auto= df_regions_auto[df_regions_auto.duplicated(subset=["ключ_клиента"], keep=False)]

In [59]:
df_moscow_gd_grouped = df_moscow_gd.groupby(["ключ_клиента", "активация_кэшбэка_жд_билеты"]).mean("оборот_жд_билеты")
df_moscow_edc_grouped = df_moscow_edc.groupby(["ключ_клиента", "активация_кэшбэка_образование"]).mean("оборот_образование")
df_moscow_house_grouped = df_moscow_house.groupby(["ключ_клиента", "активация_кэшбэка_дом_и_ремонт"]).mean("оборот_дом_и_ремонт")
df_moscow_sport_grouped = df_moscow_sport.groupby(["ключ_клиента", "активация_кэшбэка_спорттовары"]).mean("оборот_спорттовары")
df_moscow_animals_grouped = df_moscow_animals.groupby(["ключ_клиента", "активация_кэшбэка_животные"]).mean("оборот_животные")
df_moscow_flowers_grouped = df_moscow_flowers.groupby(["ключ_клиента", "активация_кэшбэка_цветы"]).mean("оборот_цветы")
df_moscow_fastfood_grouped = df_moscow_fastfood.groupby(["ключ_клиента", "активация_кэшбэка_фастфуд"]).mean("оборот_фастфуд")
df_moscow_carsharing_grouped = df_moscow_carsharing.groupby(["ключ_клиента", "активация_кэшбэка_каршеринг"]).mean("оборот_каршеринг")
df_moscow_auto_grouped = df_moscow_auto.groupby(["ключ_клиента", "активация_кэшбэка_аренда_авто"]).mean("оборот_аренда_авто")
df_moscow_gd_grouped_perc = ((sum(list(df_moscow_gd_grouped.values[i+1] > 1.05 * df_moscow_gd_grouped.values[i] for i in range(0,len(df_moscow_gd_grouped.values)-1,2))) / len(df_moscow_gd_grouped)*200)[0])
df_moscow_edc_grouped_perc = ((sum(list(df_moscow_edc_grouped.values[i+1] > 1.05 * df_moscow_edc_grouped.values[i] for i in range(0,len(df_moscow_edc_grouped.values)-1,2))) / len(df_moscow_edc_grouped)*200)[0])
df_moscow_house_grouped_perc = ((sum(list(df_moscow_house_grouped.values[i+1] > 1.05* df_moscow_house_grouped.values[i] for i in range(0,len(df_moscow_house_grouped.values)-1,2))) / len(df_moscow_house_grouped)*200)[0])
df_moscow_sport_grouped_perc = ((sum(list(df_moscow_sport_grouped.values[i+1] > 1.05 * df_moscow_sport_grouped.values[i] for i in range(0,len(df_moscow_sport_grouped.values)-1,2))) / len(df_moscow_sport_grouped)*200)[0])
df_moscow_animals_grouped_perc = ((sum(list(df_moscow_animals_grouped.values[i+1] >1.05 * df_moscow_animals_grouped.values[i] for i in range(0,len(df_moscow_animals_grouped.values)-1,2))) / len(df_moscow_animals_grouped)*200)[0])
df_moscow_fastfood_grouped_perc = ((sum(list(df_moscow_fastfood_grouped.values[i+1] > 1.05 *df_moscow_fastfood_grouped.values[i] for i in range(0,len(df_moscow_fastfood_grouped.values)-1,2))) / len(df_moscow_fastfood_grouped)*200)[0])
df_moscow_flowers_grouped_perc = ((sum(list(df_moscow_flowers_grouped.values[i+1] > 1.05 *df_moscow_flowers_grouped.values[i] for i in range(0,len(df_moscow_flowers_grouped.values)-1,2))) / len(df_moscow_flowers_grouped)*200)[0])
df_moscow_carsharing_grouped_perc = ((sum(list(df_moscow_carsharing_grouped.values[i+1] >1.05 * df_moscow_carsharing_grouped.values[i] for i in range(0,len(df_moscow_carsharing_grouped.values)-1,2))) / len(df_moscow_carsharing_grouped)*200)[0])
df_moscow_auto_grouped_perc = ((sum(list(df_moscow_auto_grouped.values[i+1] >1.05 * df_moscow_auto_grouped.values[i] for i in range(0,len(df_moscow_auto_grouped.values)-1,2))) / len(df_moscow_auto_grouped)*200)[0])
df_saint_gd_grouped = df_saint_gd.groupby(["ключ_клиента", "активация_кэшбэка_жд_билеты"]).mean("оборот_жд_билеты")
df_saint_edc_grouped = df_saint_edc.groupby(["ключ_клиента", "активация_кэшбэка_образование"]).mean("оборот_образование")
df_saint_flowers_grouped = df_saint_flowers.groupby(["ключ_клиента", "активация_кэшбэка_цветы"]).mean("оборот_цветы")
df_saint_house_grouped = df_saint_house.groupby(["ключ_клиента", "активация_кэшбэка_дом_и_ремонт"]).mean("оборот_дом_и_ремонт")
df_saint_sport_grouped = df_saint_sport.groupby(["ключ_клиента", "активация_кэшбэка_спорттовары"]).mean("оборот_спорттовары")
df_saint_animals_grouped = df_saint_animals.groupby(["ключ_клиента", "активация_кэшбэка_животные"]).mean("оборот_животные")
df_saint_fastfood_grouped = df_saint_fastfood.groupby(["ключ_клиента", "активация_кэшбэка_фастфуд"]).mean("оборот_фастфуд")
df_saint_carsharing_grouped = df_saint_carsharing.groupby(["ключ_клиента", "активация_кэшбэка_каршеринг"]).mean("оборот_каршеринг")
df_saint_auto_grouped = df_saint_auto.groupby(["ключ_клиента", "активация_кэшбэка_аренда_авто"]).mean("оборот_аренда_авто")
df_saint_gd_grouped_perc = ((sum(list(df_saint_gd_grouped.values[i+1] > 1.05 *df_saint_gd_grouped.values[i] for i in range(0,len(df_saint_gd_grouped.values)-1,2))) / len(df_saint_gd_grouped)*200)[0])
df_saint_edc_grouped_perc = ((sum(list(df_saint_edc_grouped.values[i+1] > 1.05 *df_saint_edc_grouped.values[i] for i in range(0,len(df_saint_edc_grouped.values)-1,2))) / len(df_saint_edc_grouped)*200)[0])
df_saint_house_grouped_perc = ((sum(list(df_saint_house_grouped.values[i+1] > 1.05 *df_saint_house_grouped.values[i] for i in range(0,len(df_saint_house_grouped.values)-1,2))) / len(df_saint_house_grouped)*200)[0])
df_saint_sport_grouped_perc = ((sum(list(df_saint_sport_grouped.values[i+1] >1.05 * df_saint_sport_grouped.values[i] for i in range(0,len(df_saint_sport_grouped.values)-1,2))) / len(df_saint_sport_grouped)*200)[0])
df_saint_animals_grouped_perc = ((sum(list(df_saint_animals_grouped.values[i+1] > 1.05 *df_saint_animals_grouped.values[i] for i in range(0,len(df_saint_animals_grouped.values)-1,2))) / len(df_saint_animals_grouped)*200)[0])
df_saint_fastfood_grouped_perc = ((sum(list(df_saint_fastfood_grouped.values[i+1] > 1.05 *df_saint_fastfood_grouped.values[i] for i in range(0,len(df_saint_fastfood_grouped.values)-1,2))) / len(df_saint_fastfood_grouped)*200)[0])
df_saint_flowers_grouped_perc = ((sum(list(df_saint_flowers_grouped.values[i+1] > 1.05 *df_saint_flowers_grouped.values[i] for i in range(0,len(df_saint_flowers_grouped.values)-1,2))) / (len(df_saint_flowers_grouped)*200))[0])
df_saint_carsharing_grouped_perc = ((sum(list(df_saint_carsharing_grouped.values[i+1] > 1.05 *df_saint_carsharing_grouped.values[i] for i in range(0,len(df_saint_carsharing_grouped.values)-1,2))) / len(df_saint_carsharing_grouped)*200)[0])
df_saint_auto_grouped_perc = 0 # нет данных
df_regions_gd_grouped = df_regions_gd.groupby(["ключ_клиента", "активация_кэшбэка_жд_билеты"]).mean("оборот_жд_билеты")
df_regions_flowers_grouped = df_regions_flowers.groupby(["ключ_клиента", "активация_кэшбэка_цветы"]).mean("оборот_цветы")
df_regions_edc_grouped = df_regions_edc.groupby(["ключ_клиента", "активация_кэшбэка_образование"]).mean("оборот_образование")
df_regions_house_grouped = df_regions_house.groupby(["ключ_клиента", "активация_кэшбэка_дом_и_ремонт"]).mean("оборот_дом_и_ремонт")
df_regions_sport_grouped = df_regions_sport.groupby(["ключ_клиента", "активация_кэшбэка_спорттовары"]).mean("оборот_спорттовары")
df_regions_animals_grouped = df_regions_animals.groupby(["ключ_клиента", "активация_кэшбэка_животные"]).mean("оборот_животные")
df_regions_fastfood_grouped = df_regions_fastfood.groupby(["ключ_клиента", "активация_кэшбэка_фастфуд"]).mean("оборот_фастфуд")
df_regions_carsharing_grouped = df_regions_carsharing.groupby(["ключ_клиента", "активация_кэшбэка_каршеринг"]).mean("оборот_каршеринг")
df_regions_auto_grouped = df_regions_auto.groupby(["ключ_клиента", "активация_кэшбэка_аренда_авто"]).mean("оборот_аренда_авто")
df_regions_gd_grouped_perc = ((sum(list(df_regions_gd_grouped.values[i+1] >1.05 * df_regions_gd_grouped.values[i] for i in range(0,len(df_regions_gd_grouped.values)-1,2))) / len(df_regions_gd_grouped)*200)[0])
df_regions_edc_grouped_perc = ((sum(list(df_regions_edc_grouped.values[i+1] >1.05 * df_regions_edc_grouped.values[i] for i in range(0,len(df_regions_edc_grouped.values)-1,2))) / len(df_regions_edc_grouped)*200)[0])
df_regions_house_grouped_perc = ((sum(list(df_regions_house_grouped.values[i+1] >1.05 * df_regions_house_grouped.values[i] for i in range(0,len(df_regions_house_grouped.values)-1,2))) / len(df_regions_house_grouped)*200)[0])
df_regions_sport_grouped_perc = ((sum(list(df_regions_sport_grouped.values[i+1] > 1.05 *df_regions_sport_grouped.values[i] for i in range(0,len(df_regions_sport_grouped.values)-1,2))) / len(df_regions_sport_grouped)*200)[0])
df_regions_animals_grouped_perc = ((sum(list(df_regions_animals_grouped.values[i+1] > 1.05 *df_regions_animals_grouped.values[i] for i in range(0,len(df_regions_animals_grouped.values)-1,2))) / len(df_regions_animals_grouped)*200)[0])
df_regions_fastfood_grouped_perc = ((sum(list(df_regions_fastfood_grouped.values[i+1] > 1.05 *df_regions_fastfood_grouped.values[i] for i in range(0,len(df_regions_fastfood_grouped.values)-1,2))) / len(df_regions_fastfood_grouped)*200)[0])
df_regions_flowers_grouped_perc = ((sum(list(df_regions_flowers_grouped.values[i+1] > 1.05 *df_regions_flowers_grouped.values[i] for i in range(0,len(df_regions_flowers_grouped.values)-1,2))) / len(df_moscow_flowers_grouped)*200)[0])
df_regions_carsharing_grouped_perc = 0 # нет данных
df_regions_auto_grouped_perc = 0 # нет данных

In [60]:
df_moscow_gd_grouped

                                          оборот_жд_билеты
ключ_клиента активация_кэшбэка_жд_билеты
2213         0.0                                   24517.4
             1.0                                   45418.0
1104727      0.0                                   12695.6
             1.0                                   32779.0
1116891      0.0                                       0.0
...                                                    ...
1002607234   1.0                                       0.0
1002997975   0.0                                       0.0
             1.0                                       0.0
1005319581   0.0                                     540.0
             1.0                                       0.0

[3660 rows x 1 columns]

In [61]:
print(df_regions_gd_grouped_perc,df_regions_edc_grouped_perc,df_regions_house_grouped_perc,df_regions_sport_grouped_perc, df_regions_animals_grouped_perc,
      df_regions_fastfood_grouped_perc,df_regions_flowers_grouped_perc,df_regions_carsharing_grouped_perc,df_regions_auto_grouped_perc,df_moscow_gd_grouped_perc,df_moscow_edc_grouped_perc,df_moscow_house_grouped_perc,df_moscow_sport_grouped_perc, df_moscow_animals_grouped_perc,
      df_moscow_fastfood_grouped_perc,df_moscow_flowers_grouped_perc,df_moscow_carsharing_grouped_perc,df_moscow_auto_grouped_perc,df_saint_gd_grouped_perc,df_saint_edc_grouped_perc,df_saint_house_grouped_perc,df_saint_sport_grouped_perc, df_saint_animals_grouped_perc,
      df_saint_fastfood_grouped_perc,df_saint_flowers_grouped_perc,df_saint_carsharing_grouped_perc,df_saint_auto_grouped_perc)

42.84284284284284 46.96048632218845 40.06359300476948 34.74683544303797 46.44607843137255 40.0 35.23809523809524 0 0 45.13661202185793 48.75148632580262 35.05535055350554 28.474320241691842 45.28763769889841 39.823008849557525 41.34920634920635 42.02127659574468 7.926829268292683 45.78005115089514 54.69613259668509 38.35616438356164 32.89902280130293 48.9451476793249 53.84615384615385 0.0011416666666666667 39.53488372093023 0

In [64]:
pd.DataFrame({'Регионы': [df_regions_gd_grouped_perc,df_regions_edc_grouped_perc,df_regions_house_grouped_perc,df_regions_sport_grouped_perc, df_regions_animals_grouped_perc,
      df_regions_fastfood_grouped_perc,df_regions_flowers_grouped_perc,df_regions_carsharing_grouped_perc,df_regions_auto_grouped_perc],
              'Москва': [df_moscow_gd_grouped_perc,df_moscow_edc_grouped_perc,df_moscow_house_grouped_perc,df_moscow_sport_grouped_perc, df_moscow_animals_grouped_perc,
      df_moscow_fastfood_grouped_perc,df_moscow_flowers_grouped_perc,df_moscow_carsharing_grouped_perc,df_moscow_auto_grouped_perc],
              'Питер': [df_saint_gd_grouped_perc,df_saint_edc_grouped_perc,df_saint_house_grouped_perc,df_saint_sport_grouped_perc, df_saint_animals_grouped_perc,
      df_saint_fastfood_grouped_perc,df_saint_flowers_grouped_perc,df_saint_carsharing_grouped_perc,df_saint_auto_grouped_perc]}).to_excel('regions_artem.xlsx')

In [63]:
for c in [df_regions_gd_grouped,df_regions_edc_grouped,df_regions_house_grouped,df_regions_sport_grouped, df_regions_animals_grouped,
      df_regions_fastfood_grouped,df_regions_flowers_grouped,df_regions_carsharing_grouped,df_regions_auto_grouped,df_moscow_gd_grouped,df_moscow_edc_grouped,df_moscow_house_grouped,df_moscow_sport_grouped, df_moscow_animals_grouped,
      df_moscow_fastfood_grouped,df_moscow_flowers_grouped,df_moscow_carsharing_grouped,df_moscow_auto_grouped,df_saint_gd_grouped,df_saint_edc_grouped,df_saint_house_grouped,df_saint_sport_grouped, df_saint_animals_grouped,
      df_saint_fastfood_grouped,df_saint_flowers_grouped,df_saint_carsharing_grouped,df_saint_auto_grouped]:
    print(len(c))

1998
1316
1258
3160
1632
190
2144
110
76
3660
1682
1084
2648
1634
226
2520
376
328
782
362
292
614
474
26
600
86
54